package systeminfo.telas;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import systeminfo.dal.ModuloConexao;

/**
 *
 * @author Nogara
 */
public class TelaPesquisaCidade extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    String sql1 = null;
    
    private static TelaPesquisaCidade TelaPesqCid;
    
    public static TelaPesquisaCidade getInstancia() {
        if (TelaPesqCid == null) {
            TelaPesqCid = new TelaPesquisaCidade();
        }
        return TelaPesqCid;
    }

    /**
     * Creates new form TelaPesquisaCidade
     */
    public TelaPesquisaCidade() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    // metodo de pesquisar material com filtro
    private void pesquisa_cidade() {
        String sql = "select idcidade as Codigo, cidNome as 'Cidade', cidIBGE as 'IBGE', cidCEP as 'CEP', cidBairro as 'Bairro', cidEstado as 'Estado', cidPais as 'País', cidSigla as Sigla from tbcidade where cidNome like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtPesqCidade.getText() + "%");
            rs = pst.executeQuery();
            tblPesqResult.setModel(DbUtils.resultSetToTableModel(rs));
            tblPesqResult.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblPesqResult.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblPesqResult.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblPesqResult.getColumnModel().getColumn(3).setPreferredWidth(180);
            tblPesqResult.getColumnModel().getColumn(4).setPreferredWidth(180);
            tblPesqResult.getColumnModel().getColumn(5).setPreferredWidth(60);
            tblPesqResult.getColumnModel().getColumn(6).setPreferredWidth(180);
            tblPesqResult.getColumnModel().getColumn(7).setPreferredWidth(100);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
// metodo para setar os campos dos formularios com o conteudo da tabela

    public void setar_campos() {
        txtPesqCidade.setText(null);
        int setar = tblPesqResult.getSelectedRow();
        txtPesqCidCodigo.setText(tblPesqResult.getModel().getValueAt(setar, 0).toString());
        //manipula os objetos da tela de cadastro de cidade que foram declarados publicos
        TelaCadCidade.txtCadCidCodigo.setText(tblPesqResult.getModel().getValueAt(setar, 0).toString());
        TelaCadCidade.txtCadCid.setText(tblPesqResult.getModel().getValueAt(setar, 1).toString());
        TelaCadCidade.txtCadCidIBGE.setText(tblPesqResult.getModel().getValueAt(setar, 2).toString());
        TelaCadCidade.txtCadCidCEP.setText(tblPesqResult.getModel().getValueAt(setar, 3).toString());
        TelaCadCidade.txtCadCidBairro.setText(tblPesqResult.getModel().getValueAt(setar, 4).toString());
        TelaCadCidade.cboCadEstado.setSelectedItem(tblPesqResult.getModel().getValueAt(setar, 5).toString());
        TelaCadCidade.cboCadPais.setSelectedItem(tblPesqResult.getModel().getValueAt(setar, 6).toString());
        TelaCadCidade.txtCadCidSigla.setText(tblPesqResult.getModel().getValueAt(setar, 7).toString());
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        txtPesqCidade = new javax.swing.JTextField();
        txtPesqCidCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesqResult = new javax.swing.JTable();
        btnPesqCancelar = new javax.swing.JButton();
        btnPesqConfirmar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Pesquisa de Cidade");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite a Cidade:"));

        txtPesqCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqCidadeKeyReleased(evt);
            }
        });

        txtPesqCidCodigo.setEditable(false);

        jLabel1.setText("* Codigo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtPesqCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesqCidCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtPesqCidade)
                .addComponent(txtPesqCidCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        tblPesqResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cidade", "IBGE", "CEP", "Bairro", "Estado", "País", "Sigla"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPesqResult.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPesqResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesqResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesqResult);
        if (tblPesqResult.getColumnModel().getColumnCount() > 0) {
            tblPesqResult.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblPesqResult.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblPesqResult.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblPesqResult.getColumnModel().getColumn(3).setPreferredWidth(180);
            tblPesqResult.getColumnModel().getColumn(4).setPreferredWidth(180);
            tblPesqResult.getColumnModel().getColumn(5).setPreferredWidth(60);
            tblPesqResult.getColumnModel().getColumn(6).setPreferredWidth(180);
            tblPesqResult.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        btnPesqCancelar.setText("Cancelar");
        btnPesqCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqCancelarActionPerformed(evt);
            }
        });

        btnPesqConfirmar.setText("Confirmar");
        btnPesqConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnPesqConfirmar)
                        .addGap(108, 108, 108)
                        .addComponent(btnPesqCancelar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesqConfirmar)
                    .addComponent(btnPesqCancelar))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        setBounds(250, 75, 636, 561);
    }// </editor-fold>//GEN-END:initComponents


    private void tblPesqResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesqResultMouseClicked
        // chamando o metodo setar campos
        setar_campos();
    }//GEN-LAST:event_tblPesqResultMouseClicked

    private void txtPesqCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqCidadeKeyReleased
        // chamando o metodo pesquisar
        pesquisa_cidade();
    }//GEN-LAST:event_txtPesqCidadeKeyReleased

    private void btnPesqConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqConfirmarActionPerformed
        // confirma a seleção
        //validar campos obrigatorios
        if (txtPesqCidCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione a Cidade!");
        } else {
            dispose();
        }
    }//GEN-LAST:event_btnPesqConfirmarActionPerformed

    private void btnPesqCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqCancelarActionPerformed
        // cancelar a tela
        TelaCadCidade.txtCadCid.setText(null);
        TelaCadCidade.txtCadCidCEP.setText(null);
        TelaCadCidade.txtCadCidBairro.setText(null);
        TelaCadCidade.txtCadCidIBGE.setText(null);
        TelaCadCidade.txtCadCidCodigo.setText(null);
        TelaCadCidade.txtCadCidSigla.setText(null);
        dispose();
        TelaCadCidade.btnSalvar.setEnabled(true);
        TelaCadCidade.btnEditar.setEnabled(false);
        TelaCadCidade.btnRemover.setEnabled(false);
    }//GEN-LAST:event_btnPesqCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesqCancelar;
    private javax.swing.JButton btnPesqConfirmar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPesqResult;
    public static javax.swing.JTextField txtPesqCidCodigo;
    private javax.swing.JTextField txtPesqCidade;
    // End of variables declaration//GEN-END:variables
}
