package systeminfo.telas;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import systeminfo.dal.Gerentedetelas;
import systeminfo.dal.ModuloConexao;
import static systeminfo.telas.TelaPrincipal.Desktop;

/**
 *
 * @author Nutrizon
 */
public class TelaPesquisaCidadeCadEstrutura extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    String sql1 = null;
    
    Gerentedetelas gerentedetelas;

    private static TelaPesquisaCidadeCadEstrutura telaCad;

    public static TelaPesquisaCidadeCadEstrutura getInstancia() {
        if (telaCad == null) {
            telaCad = new TelaPesquisaCidadeCadEstrutura();
        }
        return telaCad;
    }

    /**
     * Creates new form TelaPesquisaCidade
     */
    public TelaPesquisaCidadeCadEstrutura() {
        initComponents();
        conexao = ModuloConexao.conector();
        TelaPesquisaCidadeCadEstrutura.txtPesqCidade.setText(null);
        TelaPesquisaCidadeCadEstrutura.txtPesqCidCodigo.setText(null);
        TelaPesquisaCidadeCadEstrutura.txtPesqCidade.setFocusable(true);
        tblPesqResult.setEnabled(true);
        
        this.gerentedetelas = new Gerentedetelas(Desktop);

    }

    // metodo de pesquisar com filtro
    private void pesquisa_cidade() {
        String sql = "select idcidade as Codigo, cidNome as 'Cidade', cidEstado as 'Estado', cidPais as 'País' from tbcidade where cidNome like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtPesqCidade.getText() + "%");
            rs = pst.executeQuery();
            tblPesqResult.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
// metodo para setar os campos dos formularios com o conteudo da tabela

    public void setar_campos() {
        txtPesqCidade.setText(null);
        int setar = tblPesqResult.getSelectedRow();
        txtPesqCidCodigo.setText(tblPesqResult.getModel().getValueAt(setar, 0).toString());
        txtPesqCidade.setText(tblPesqResult.getModel().getValueAt(setar, 1).toString());
        //manipula os objetos da tela de cadastro de cidade que foram declarados publicos
        TelaCadEstruturas.txtCadEstruturaIdCidade.setText(tblPesqResult.getModel().getValueAt(setar, 0).toString());
        TelaCadEstruturas.txtCadNomeCidade.setText(tblPesqResult.getModel().getValueAt(setar, 1).toString());
        TelaCadEstruturas.txtCadEstruturaEstado.setText(tblPesqResult.getModel().getValueAt(setar, 2).toString());

        String sql1 = "select idcidade as Codigo, cidNome as 'Cidade', cidEstado as 'Estado', cidPais as 'País' from tbcidade where idcidade = ? group by cidEstado, cidNome";
        try {
            pst1 = conexao.prepareStatement(sql1);
            pst1.setString(1, txtPesqCidade.getText());
            //pst1.setString(0, txtPesqCidCodigo.getText());
            rs1 = pst1.executeQuery();
            tblPesqResult.setModel(DbUtils.resultSetToTableModel(rs1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        txtPesqCidade = new javax.swing.JTextField();
        txtPesqCidCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesqResult = new javax.swing.JTable();
        btnPesqCancelar = new javax.swing.JButton();
        btnPesqConfirmar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Pesquisa de Cidade");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite a Cidade:"));

        txtPesqCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqCidadeKeyReleased(evt);
            }
        });

        txtPesqCidCodigo.setEditable(false);

        jLabel1.setText("* Codigo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtPesqCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesqCidCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtPesqCidade)
                .addComponent(txtPesqCidCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        tblPesqResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Cidade", "Estado", "País"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPesqResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesqResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesqResult);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPesqCancelar.setText("Cancelar");
        btnPesqCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqCancelarActionPerformed(evt);
            }
        });

        btnPesqConfirmar.setText("Confirmar");
        btnPesqConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqConfirmarActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar Cidade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesqCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesqConfirmar)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesqConfirmar)
                    .addComponent(btnPesqCancelar)
                    .addComponent(jButton1))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setBounds(250, 75, 561, 358);
    }// </editor-fold>//GEN-END:initComponents


    private void tblPesqResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesqResultMouseClicked
        // chamando o metodo setar campos
        setar_campos();
    }//GEN-LAST:event_tblPesqResultMouseClicked

    private void txtPesqCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqCidadeKeyReleased
        // chamando o metodo pesquisar
        pesquisa_cidade();
    }//GEN-LAST:event_txtPesqCidadeKeyReleased

    private void btnPesqConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqConfirmarActionPerformed
        // confirma a seleção
        //validar campos obrigatorios
        if (txtPesqCidCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione a Cidade!");
        } else {
            dispose();
        }
    }//GEN-LAST:event_btnPesqConfirmarActionPerformed

    private void btnPesqCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqCancelarActionPerformed
        // cancelar a tela
        // TelaCadEstruturas.txtCadTorresIdCidade.setText(null);
        TelaCadEstruturas.txtCadNomeCidade.setText(null);
        dispose();
        TelaCadEstruturas.btnAdicionar.setEnabled(false);

        TelaCadEstruturas.btnGravar.setEnabled(true);
        TelaCadEstruturas.btnCancelar.setEnabled(true);
        TelaCadEstruturas.btnEditar.setEnabled(false);
        TelaCadEstruturas.btnRemover.setEnabled(false);
        TelaCadEstruturas.btnCadTorresPesqCidade.setEnabled(true);

    }//GEN-LAST:event_btnPesqCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // chama a tela de cadastro de cidades e estado      
        gerentedetelas.abrirjanelas(TelaCadCidade.getInstancia());

        txtPesqCidade.setText(null);
        txtPesqCidCodigo.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesqCancelar;
    private javax.swing.JButton btnPesqConfirmar;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPesqResult;
    public static javax.swing.JTextField txtPesqCidCodigo;
    public static javax.swing.JTextField txtPesqCidade;
    // End of variables declaration//GEN-END:variables
}
